export const SPICES = [
  {
    slug: 'bay-leaves',
    name: 'Bay Leaves',
    hindiName: 'Tejpatta',
    emoji: '🌿',
    color: '#111111',
    tagline: 'The ancient aromatic of the Mediterranean',
    history: 'The Latin name for the bay tree is Laurus Nobilis, which is used to crown Olympic games champions at the Grand Prix. Bay leaves, which are also known as Laurel leaves, have a long and interesting history. The ancient Romans and Greeks used its leaves out of respect for its power and understood powers. This is why Greek and Roman statues of famous people usually have bay leaves growing out of their heads. Bay leaves actually originate from fresh forests and that\'s where we got the modern-day equivalent putting on your head beautifully. The Indian bay leaves or Tejpatta comes from a tree called the Laurel family in the bay forests found in the West that have a notable shape and a taste similar to cinnamon or cloves.',
    cultivation: 'Bay leaves can be grown as a culinary herb at home but they look perfect growing outdoors where their natural Mediterranean habitat. It prefers rich, well-drained soil and semi-shades and grows up to a height of 7m. The growth rate is very slow but once it starts growing, it becomes more vigorous after a couple of years old. The leaves should be dried before you cook bay leaves but know the time the leaves are picked is around 30 to 60 hours from the time the leaves are gathered.',
    usage: 'Bay leaf is ideal for seasoning stews and soups. It is used in stock well-flavoured strong, condensed dishes and all over the world soils in many homes. It can also be used with many other herbs and spices. In many homes, it has been proven that it can used the same way as dried herbs and spices, they shouldn\'t be stored in the spice drawer or medicine. Instead they should be placed in the freezer so they retain flavour as much. Remove and serve on a finish opened as sauces or baked potatoes or the same added to other herbs (types food). However, quickly lose its potency.',
    benefits: 'The oil extracted from bay leaves, called bay leaf oil, has medicinal properties and is used to treat several diseases. It is a known that be anti-bacterial, anti-fungal, anti-inflammatory, diuretic, and anti-oxidant. And that it\'s also known that enzymes found in the bay leaves can help ease digestion. Extracts made from bay leaves can help reduce joint inflammation.',
  },
  {
    slug: 'black-pepper',
    name: 'Black Pepper',
    hindiName: 'Kali Mirch',
    emoji: '⚫',
    color: '#2C3E50',
    tagline: 'The King of Spices',
    history: 'Black pepper is one of the most widely traded spices in the world and has been used since ancient times. Native to Kerala, India, it was so valuable in medieval Europe that it was used as currency. Black pepper is from the Piperaceae family and is native to the Malabar coast of India.',
    cultivation: 'Black pepper vines are perennial climbers that require a warm, humid climate. They are grown on support trees or poles and take 3–4 years to bear fruit. India, Vietnam, Indonesia, and Brazil are the world\'s leading producers. Pepper berries are harvested when one or two start to turn red, then sun-dried to blacken.',
    usage: 'Black pepper can be used in virtually every dish — from simple salads to elaborate gourmet meals. Ground black pepper is the most common form, but whole peppercorns are preferred for pickling, marinades, and long-cooked dishes where the flavour is slowly released.',
    benefits: 'Black pepper contains piperine, an alkaloid with potent antioxidant properties. It has been shown to enhance bioavailability of other nutrients, particularly curcumin. It also has anti-inflammatory, antibacterial, and digestive-support benefits.',
  },
  {
    slug: 'cardamoms',
    name: 'Cardamoms',
    hindiName: 'Elaichi',
    emoji: '🫙',
    color: '#1A6B3E',
    tagline: 'The Queen of Spices — prized since antiquity',
    history: 'Cardamom is a spice that comes from the seeds of various plants in the ginger family. This spice is native to Southern India, and is also grown across the Tropics. Known as the Queen of Spices, it has been traded since ancient times and was highly prized in Ancient Egypt and Rome.',
    cultivation: 'Cardamom grows in tropical forests at altitudes of 600–1,500m. It thrives in rich, loamy soil with good water retention. Plants take 2–3 years to produce their first yield and continue bearing for up to 12 years. India\'s Idukki district in Kerala is the traditional cardamom heartland.',
    usage: 'Green cardamom is used widely in Indian and Middle Eastern cuisines — in chai, biryanis, desserts, and spice blends. Black cardamom is used in savoury dishes, curries, and rice. It is an essential ingredient in many spice blends including garam masala.',
    benefits: 'Cardamom is rich in antioxidants and has digestive properties. It is traditionally used to freshen breath, improve digestion, and has anti-inflammatory effects. Studies suggest it may lower blood pressure and have antibacterial properties.',
  },
  {
    slug: 'chilli',
    name: 'Chilli',
    hindiName: 'Lal Mirch',
    emoji: '🌶',
    color: '#111111',
    tagline: 'The spice that ignites the world',
    history: 'Chilli peppers originated in the Americas and were cultivated by the Aztecs and Incas for thousands of years. After Christopher Columbus brought them to Europe in the 1490s, they spread globally with extraordinary speed. India is now the world\'s largest producer and exporter of chillies.',
    cultivation: 'Chillies require a warm, well-drained growing environment. India\'s major growing states include Andhra Pradesh, Telangana, Karnataka, and Rajasthan. The Guntur district of Andhra Pradesh alone produces a significant proportion of India\'s chilli output. Harvest is done by hand, with 3–4 pickings per season.',
    usage: 'Chilli is used in virtually every cuisine globally. Dried whole chillies, chilli powder, chilli flakes, and chilli paste are all common. In Indian cuisine it is indispensable — from spice blends and curries to pickles and chutneys.',
    benefits: 'Chillies are rich in Vitamin C, Vitamin B6, iron, copper, and potassium. Capsaicin, the active compound, has powerful anti-inflammatory and pain-relief properties. It boosts metabolism and has been shown to have cardiovascular benefits.',
  },
  {
    slug: 'cinnamon',
    name: 'Cinnamon',
    hindiName: 'Dalchini',
    emoji: '🌰',
    color: '#8B4513',
    tagline: 'Ancient spice of warmth and healing',
    history: 'Cinnamon comes from the inner bark of several tree species. It is one of the oldest known spices, mentioned in Chinese writing from 2700 BC and in the Bible. Ceylon cinnamon (true cinnamon) and Cassia cinnamon are the two main commercial types. Ceylon cinnamon is native to Sri Lanka.',
    cultivation: 'Cinnamon trees are grown in tropical climates and harvested twice a year. The bark is stripped in the rainy season when it is most flexible, then dried and rolled into the familiar quill shape. Sri Lanka, India, China, Indonesia, and Vietnam are the major producers.',
    usage: 'Cinnamon is used in both sweet and savoury cooking worldwide. In Indian cuisine, it is a key component of garam masala and biryani. It is widely used in baking, beverages, and confectionery in Western countries. Cinnamon sticks and powder are both common forms.',
    benefits: 'Cinnamon has potent antioxidant and anti-inflammatory properties. It is well studied for its ability to lower blood sugar levels and improve insulin sensitivity, making it particularly beneficial for type 2 diabetics. It also has antimicrobial properties.',
  },
  {
    slug: 'cloves',
    name: 'Cloves',
    hindiName: 'Laung',
    emoji: '🌸',
    color: '#5D4037',
    tagline: 'The intensely aromatic nail-flower',
    history: 'Cloves are the dried flower buds of the clove tree, native to the Maluku Islands (Spice Islands) of Indonesia. They were among the most valuable spices in medieval Europe and were a catalyst for the Age of Exploration. Portuguese, Dutch, and British traders fought wars to control the clove trade.',
    cultivation: 'Clove trees grow in tropical environments and begin bearing fruit after 6–7 years. They can produce cloves for up to 100 years. Major producing countries include Indonesia, Madagascar, Tanzania, and Sri Lanka. Flower buds are hand-picked while still pink and then sun-dried to turn dark brown.',
    usage: 'Cloves are used whole or ground in Indian spice blends (garam masala, biryani), as well as in Indonesian, African, and European cuisines. Clove oil is widely used in dentistry for its anaesthetic properties. They are also a key ingredient in mulled wine and holiday baking.',
    benefits: 'Cloves are one of the most antioxidant-rich spices known. Eugenol, the primary active compound, has powerful anti-inflammatory, antimicrobial, and analgesic properties. Cloves are also used for dental pain relief and to improve digestive health.',
  },
  {
    slug: 'dhaniya',
    name: 'Dhaniya (Coriander)',
    hindiName: 'Dhania',
    emoji: '🌿',
    color: '#388E3C',
    tagline: 'One plant, two spices — seed and leaf',
    history: 'Coriander is one of the world\'s oldest spices, found in Egyptian tombs dating to 3,000 years ago and mentioned in ancient Sanskrit texts. It is native to regions spanning from Southern Europe to Southwest Asia. India, Morocco, and Canada are the world\'s leading producers.',
    cultivation: 'Coriander grows best in cool, dry climates. In India, Rajasthan, Madhya Pradesh, and Gujarat are the major growing states. The plant reaches maturity in 45–60 days. Seeds are harvested when they turn brown, then dried and threshed. Dual harvest (leaf + seed) is common in smallholder farming.',
    usage: 'Coriander seeds are ground for spice blends, curry powders, and marinades. Coriander leaves (cilantro) are used fresh as a garnish across Indian, Mexican, and Southeast Asian cuisines. Coriander is one of the most consumed herbs globally.',
    benefits: 'Coriander seeds are a good source of dietary fibre, manganese, iron, and magnesium. They have antioxidant and anti-inflammatory properties and may help lower blood sugar and cholesterol. The essential oil has demonstrated antibacterial activity.',
  },
  {
    slug: 'ginger',
    name: 'Ginger',
    hindiName: 'Adrak',
    emoji: '🫚',
    color: '#F57F17',
    tagline: 'The universal remedy of ancient medicine',
    history: 'Ginger is a flowering plant that traces its origins back to Southeast Asia. It belongs to the Zingiberaceae family and is closely related to turmeric, cardamom, and galangal. Ginger has been used for over 5,000 years both as a culinary ingredient and as a medicine.',
    cultivation: 'Ginger is a tropical plant that grows from rhizomes. It requires well-drained, fertile soil and a warm, humid climate. India is the world\'s largest producer of ginger, with Kerala, Meghalaya, and Karnataka being major production states. Rhizomes are planted in spring and harvested in 8–10 months.',
    usage: 'Fresh ginger is used extensively in Asian cooking — in curries, stir-fries, soups, and marinades. Dried ground ginger is used in baking, spice blends, and beverages. Ginger tea is one of the most popular herbal drinks globally. Crystallised and pickled ginger are also widely consumed.',
    benefits: 'Ginger contains gingerols and shogaols, powerful bioactive compounds. It is well established as an anti-nausea remedy. Studies demonstrate anti-inflammatory effects, blood sugar regulation potential, and beneficial effects on digestion. It is one of the most widely studied medicinal plants.',
  },
  {
    slug: 'haldi',
    name: 'Haldi (Turmeric)',
    hindiName: 'Haldi',
    emoji: '💛',
    color: '#F9A825',
    tagline: 'The golden spice of ancient healing',
    history: 'Turmeric is a rhizomatous herbaceous perennial plant and member of the ginger family. It is native to Southeast Asia and is grown widely in India, which produces nearly 80% of the world\'s turmeric. It has been used in Ayurvedic medicine for at least 4,000 years.',
    cultivation: 'Turmeric requires a warm, humid climate and well-drained, loamy soil. India\'s Andhra Pradesh, Tamil Nadu, Orissa, and Maharashtra are the key growing states. Erode in Tamil Nadu is known as the "Yellow City" for its enormous turmeric trade. Rhizomes are planted in spring and harvested in 7–9 months.',
    usage: 'Turmeric is the cornerstone of Indian cooking — giving curry its characteristic golden colour. It is used in spice blends, dals, rice dishes, pickles, and beverages (golden milk / haldi doodh). Turmeric\'s curcumin content is a key driver of the global functional food market.',
    benefits: 'Curcumin, turmeric\'s primary bioactive compound, has been the subject of thousands of scientific studies. It has powerful anti-inflammatory, antioxidant, anti-cancer, and neuroprotective properties. Bioavailability is enhanced when consumed with black pepper (piperine).',
  },
  {
    slug: 'jeera',
    name: 'Jeera (Cumin)',
    hindiName: 'Jeera',
    emoji: '🌾',
    color: '#795548',
    tagline: 'The earthy warmth of the Middle East and India',
    history: 'Cumin is a member of the parsley family that is native to the East Mediterranean and South Asia. It\'s a small, flowering herb belonging to the Apiaceae family of the genus Cuminum. Archaeological evidence suggests cumin cultivation dating back to at least 5,000 years in Syria.',
    cultivation: 'Cumin grows best in a hot, dry climate. In India, Rajasthan and Gujarat are the dominant producers, accounting for most of the country\'s output. The plant reaches maturity in 90–120 days. Seeds are harvested when the plant yellows and dried in the sun before threshing.',
    usage: 'Cumin is one of the most widely used spices globally. It is a foundation of Indian, Mexican, North African, and Middle Eastern cuisines. Used in spice blends, curries, breads, rice, and chutneys. Cumin seeds are often tempered in hot oil to release their full flavour profile.',
    benefits: 'Cumin is an excellent source of iron, manganese, and other minerals. It has traditional use as a digestive aid and carminative. Research suggests cumin extract may help reduce blood sugar levels and has antimicrobial properties. Cumin contains antioxidants including flavonoids.',
  },
  {
    slug: 'methi',
    name: 'Methi (Fenugreek)',
    hindiName: 'Methi',
    emoji: '🌱',
    color: '#558B2F',
    tagline: 'The bitter-sweet seed of ancient herbalism',
    history: 'Fenugreek has been cultivated since antiquity — seeds were found in Tutankhamun\'s tomb and are mentioned in Egyptian papyri. It is native to the Mediterranean region and is cultivated extensively in India, which produces 80% of the global supply. Rajasthan is India\'s largest producer.',
    cultivation: 'Fenugreek is an annual plant that grows to 30–60cm height. It prefers sandy loam soil with good drainage and cool-to-warm temperatures. India\'s Rajasthan, Madhya Pradesh, and Gujarat produce the bulk of the crop. Seeds are harvested when pods turn yellow, then dried and threshed.',
    usage: 'Fenugreek seeds are used in spice blends (panch phoron, curries, pickles) and as a flavouring in artificial maple syrup. Fresh and dried fenugreek leaves (kasuri methi) are widely used in Indian cooking — added to flatbreads, curries, and vegetable dishes.',
    benefits: 'Fenugreek is well-documented for its ability to regulate blood sugar and improve insulin sensitivity. It is used traditionally to support lactation in nursing mothers. Fenugreek seeds are high in soluble fibre, which helps manage cholesterol and has digestive benefits.',
  },
  {
    slug: 'mustard',
    name: 'Mustard',
    hindiName: 'Sarson',
    emoji: '🟡',
    color: '#F9A825',
    tagline: 'The universal condiment spice',
    history: 'Mustard has been cultivated since prehistoric times. It is mentioned in the Bible, ancient Sanskrit texts, and Greek literature. India, Canada, Nepal, and Russia are the world\'s leading producers. In India, mustard is the second largest source of edible oil after groundnut.',
    cultivation: 'Mustard is a cool-season crop grown widely across North India — Rajasthan, UP, Haryana, and Madhya Pradesh are the major states. It is harvested in late winter/early spring. Seeds are threshed and cleaned before processing for oil or spice use.',
    usage: 'Mustard seeds are used as a tempering spice in South and East Indian cuisines. Ground mustard is a key ingredient in pickles and curry pastes. Mustard oil is widely used for cooking in North and East India. Western condiment mustard is also made from ground mustard seeds.',
    benefits: 'Mustard seeds are high in selenium, manganese, and omega-3 fatty acids. They have anti-inflammatory, antibacterial, and antifungal properties. Glucosinolates in mustard seeds have been studied for potential cancer-protective effects.',
  },
  {
    slug: 'saunf',
    name: 'Saunf (Fennel)',
    hindiName: 'Saunf',
    emoji: '💚',
    color: '#00796B',
    tagline: 'The digestive herb of the Mediterranean',
    history: 'Fennel is a highly aromatic perennial herb native to the Mediterranean basin. It is widely cultivated around the world and is one of the primary plants of the Apiaceae family. Fennel has been used for medicinal and culinary purposes since ancient Greek and Roman times.',
    cultivation: 'Fennel grows best in dry soils near the coast and on river banks. In India, Gujarat, Rajasthan, and Uttar Pradesh are the main producing states. Kutch in Gujarat is a premium source of high-quality fennel. The plant produces seeds in its second year and is harvested when seeds turn pale green to yellow.',
    usage: 'Fennel seeds are used extensively in Indian cooking — in spice blends, bread, pickles, and as a mouth freshener. Fennel bulbs and fronds are eaten as vegetables in Mediterranean cuisines. Fennel is also used in herbal teas, liqueurs (absinthe, ouzo), and sausage making.',
    benefits: 'Fennel has long been used as a digestive aid and carminative — reducing bloating, flatulence, and cramps. It contains anethole, which has anti-inflammatory properties. Fennel is also a good source of vitamin C, potassium, and fibre.',
  },
  {
    slug: 'white-pepper',
    name: 'White Pepper',
    hindiName: 'Safed Mirch',
    emoji: '⚪',
    color: '#9E9E9E',
    tagline: 'Black pepper\'s refined, milder cousin',
    history: 'White pepper is native to Southeast Asia and is made from the same source as black pepper — the Piper nigrum vine. The difference lies in processing: berries are allowed to fully ripen, then soaked in water to remove the outer skin, revealing the white inner core. Vietnam, Indonesia, and Brazil are major producers.',
    cultivation: 'White pepper production requires fully ripe black pepper berries that are then soaked (retting) in running water or tanks for 1–2 weeks to remove the outer hull. This makes white pepper production more labour-intensive and thus more expensive than black pepper.',
    usage: 'White pepper is preferred in light-coloured dishes like white sauces, béchamel, and cream soups where black specks would be visually undesirable. It is widely used in Chinese, French, and Scandinavian cuisines. Its flavour is slightly different from black pepper — earthy and pungent without the floral notes.',
  },
];
