export const siteConfig = {
  name: 'LV Spices',
  tagline: "India's Trusted Spice Manufacturer, Supplier & Exporter | Bulk • OEM • Private Label • Custom Blends",
  description:
    "India's trusted spice manufacturer, supplier & exporter. Bulk orders, OEM, private label, and custom blends. 50+ years of excellence. NABL, ISO 22000, FSSC 22000 certified.",
  url: 'https://lvspices.com',
  parentCompany: 'Chillito Exports',
  handle: '@cfexports',
  legacy: '50 Years',
  foundedYear: 1975,
  hq: {
    address: '12, Marine House, 93 Dr Maheshwari Road',
    city: 'Mumbai',
    pincode: '400009',
    country: 'India',
    full: '12, Marine House, 93 Dr Maheshwari Road, Mumbai 400009, India',
  },
  contact: {
    phone: '+91 7279 900 500',
    email: 'cf@lvspices.com',
    whatsapp: '+917279900500',
  },
  social: {
    twitter: 'https://twitter.com/cfexports',
    youtube: 'https://youtube.com/@cfexports',
    instagram: 'https://instagram.com/cfexports',
    facebook: 'https://facebook.com/cfexports',
    linkedin: 'https://linkedin.com/company/lvspices',
  },
  seo: {
    title: "LV Spices | India's Trusted Spice Manufacturer, Supplier & Exporter",
    description:
      "India's trusted spice manufacturer, supplier & exporter. Bulk spices, OEM, private label & custom blends. 50+ years of excellence. Cryogenic grinding, steam sterilization, NABL, ISO 22000, FSSC 22000 certified. 500+ SKUs, 40+ countries.",
    keywords: [
      "India's trusted spice manufacturer",
      'spice supplier India',
      'spice exporter India',
      'bulk spice supplier',
      'OEM spice manufacturer',
      'private label spices India',
      'custom spice blends',
      'Indian spices exporter',
      'cryogenic grinding spices',
      'spice manufacturer India',
      'premium spices',
      'LV Spices',
      'Chillito Exports',
      'steam sterilization spices',
      'CFG Science',
      'organic spices exporter',
      'FSSAI certified spices',
      'ISO 22000 spice manufacturer',
      'FSSC 22000 certified',
      'NABL accredited spice lab',
      'Sedex certified',
      'chilli powder exporter India',
      'turmeric powder manufacturer',
      'masala manufacturer India',
      'spice blending company India',
      'food grade spices India',
      'halal certified spices',
      'spice export Mumbai',
      'bulk masala supplier',
      'private label spice brand',
    ],
  },
} as const;

export type SiteConfig = typeof siteConfig;
